--- #YAML:1.0
name:                Fault
version:             1.01-2
abstract:            Useful perl modules including sophisticated diagnostic, fault and log handling and printing classes
license:             ~
author:              
    - Dale Amon
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    DBI:                           0
    Exporter:                      0
    Net::HTTP:                     0
    POSIX:                         0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
