# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Fault
version:      1.00
version_from: Makefile.PL
installdirs:  site
requires:
    DBI:                           0
    Exporter:                      0
    Net::HTTP:                     0
    POSIX:                         0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
